//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIWcfSergioJoseLuisMena.Servicepeliculas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicepeliculas.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscarPeli", ReplyAction="http://tempuri.org/IService1/buscarPeliResponse")]
        string[] buscarPeli(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscarPeli", ReplyAction="http://tempuri.org/IService1/buscarPeliResponse")]
        System.Threading.Tasks.Task<string[]> buscarPeliAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : GUIWcfSergioJoseLuisMena.Servicepeliculas.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<GUIWcfSergioJoseLuisMena.Servicepeliculas.IService1>, GUIWcfSergioJoseLuisMena.Servicepeliculas.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] buscarPeli(int id) {
            return base.Channel.buscarPeli(id);
        }
        
        public System.Threading.Tasks.Task<string[]> buscarPeliAsync(int id) {
            return base.Channel.buscarPeliAsync(id);
        }
    }
}
